apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crossplane-kubernetes-provider-role
  namespace: default
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "deployments", "replicasets", "statefulsets", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crossplane-kubernetes-provider-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crossplane-kubernetes-provider-role
subjects:
  - kind: ServiceAccount
    name: provider-kubernetes-a3cbbe355fa7
    namespace: crossplane-system
