apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: hello-world-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: hello-world-service
        namespace: default
      spec:
        selector:
          app: hello-world
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
        type: ClusterIP
  providerConfigRef:
    name: default
